id = "catppuccin-icons"
name = "Catppuccin Icons"
version = "1.17.2"
schema_version = 1
authors = ["Catppuccin <releases@catppuccin.dev>"]
description = "🦊 Soothing pastel icons for Zed"
repository = "https://github.com/tecandrew/catppuccin-zed-icons"
