id = "catppuccin-icons"
name = "Catppuccin Icons"
version = "1.21.0"
schema_version = 1
authors = ["Catppuccin <releases@catppuccin.com>"]
description = "🦊 Soothing pastel icons for Zed"
repository = "https://github.com/catppuccin/zed-icons"
