name: Sync with Zed's Icons
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 */2 * *'

jobs:
  sync:
    runs-on: ubuntu-24.04-arm
    outputs:
      zed_sha_commit: ${{ steps.zed_sha.outputs.commit }}
      updated: ${{ steps.sync.outputs.updated }}
      missing_icons: ${{ steps.sync.outputs.missing_icons }}
      n_missing_icons: ${{ steps.sync.outputs.n_missing_icons }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: 'zed-industries/zed'
          token: ${{ github.token }}
          path: zed
          sparse-checkout: |
            assets/icons/file_icons/file_types.json
          sparse-checkout-cone-mode: false

      - name: Get Zed commit SHA
        id: zed_sha
        run: |
          cd zed
          echo "commit=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          cd ..

      - name: Sync with Zed default icons
        id: sync
        run: |
          python3 ./src/sync.py
          echo "Outputs:"
          cat $GITHUB_OUTPUT

  create-PR:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-24.04-arm
    needs: sync
    if: ${{ needs.sync.outputs.updated }}
    steps:
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo install catppuccin-whiskers@=2.5.1
      - run: whiskers zed-icons.tera
      - name: Validate New Icons
        run: python3 ./src/test.py --validate
        continue-on-error: true
      - name: Create pull request
        uses: peter-evans/create-pull-request@v7
        with:
          branch: "feat/zed-sync-${{ needs.sync.outputs.zed_sha_commit }}"
          title: "feat: define icons - ${{ needs.sync.outputs.missing_icons }}"
          commit-message: "feat: define icons - ${{ needs.sync.outputs.missing_icons }}"
          body: |
            Define ${{ needs.sync.outputs.n_missing_icons }} additional icons

            ## Reference
            - https://github.com/zed-industries/zed/blob/${{ needs.sync.outputs.zed_sha_commit }}/assets/icons/file_icons/file_types.json
            - https://github.com/zed-industries/zed/tree/${{ needs.sync.outputs.zed_sha_commit }}/assets/icons/file_icons
          add-paths: |
            zed-icons.tera
            icon_themes/*.json
