name: Sync with Zed's Icons
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 */2 * *'

jobs:
  sync:
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: 'zed-industries/zed'
          token: ${{ github.token }}
          path: zed
          sparse-checkout: |
            assets/icons/file_icons/file_types.json
          sparse-checkout-cone-mode: false

      - name: Get Zed commit SHA
        id: zed_sha
        run: |
          cd zed
          echo "commit=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          cd ..

      - name: Sync with Zed default icons
        id: sync
        run: |
          python3 ./src/sync.py
          echo "Outputs:"
          cat $GITHUB_OUTPUT
      - name: Debug outputs
        run: |
          echo "Updated: ${{ steps.sync.outputs.updated }}"
          echo "Missing icons: ${{ steps.sync.outputs.missing_icons }}"
          echo "N missing icons: ${{ steps.sync.outputs.n_missing_icons }}"
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo install catppuccin-whiskers@=2.5.1
      - run: whiskers zed-icons.tera
      - name: Create pull request
        uses: peter-evans/create-pull-request@v7
        if: ${{ steps.sync.outputs.updated }}
        with:
          branch: "feat/zed-sync-${{ steps.zed_sha.outputs.commit }}"
          title: "feat: define icons - ${{ steps.sync.outputs.missing_icons }}"
          commit-message: "feat: define icons - ${{ steps.sync.outputs.missing_icons }}"
          body: |
            Define ${{ steps.sync.outputs.n_missing_icons }} additional icons

            ## Reference
            - https://github.com/zed-industries/zed/blob/${{ steps.zed_sha.outputs.commit }}/assets/icons/file_icons/file_types.json
            - https://github.com/zed-industries/zed/tree/${{ steps.zed_sha.outputs.commit }}/assets/icons/file_icons
          add-paths: |
            zed-icons.tera
            icon_themes/*.json
